version: '2'

volumes:
  dbdata:
    driver: local

services:
    battleshipgame:
        build:
            dockerfile: Dockerfile
            context: .
        working_dir: /var/www
        hostname: local
        ports:
        - 8081:80
        volumes:
        - .:/var/www
        - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
        - ./logs:/var/www/logs
        - ~/.ssh:/root/.ssh
        links:
        - database

    # database
    database:
        image: mysql:5.7
        ports:
        - 33061:3306
        environment:
        - "MYSQL_DATABASE=battleship"
        - "MYSQL_ROOT_PASSWORD=secret"
        volumes:
        - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
        - "MYSQL_USERNAME=root"
        - "MYSQL_ROOT_PASSWORD=secret"
        - "PMA_HOST=database"
        links:
        - database
        ports:
        - 8080:80
        restart: always


